apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: dev
  name: pgadmin-pvc
  labels:
    app: pgadmin

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
