apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
  - ../../secrets
  # ---
  - infrastructure/argocd
  # ---
  - infrastructure/longhorn
  # ---
  - infrastructure/rustfs
  # ---
  - infrastructure/grafana
  # ---
  - infrastructure/tailscale
  # ---
  - keycloak
  # ---
  - opencloud
  # ---
  - outline
  # ---
  - jellyfin
  # ---
  - vaultwarden
