apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: dev
  name: code-server-pvc
  labels:
    app: code-server

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
