apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: outline
  name: outline-redis
  labels:
    app: outline-redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: outline-redis
  template:
    metadata:
      labels:
        app: outline-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: outline-redis
          image: redis:8-alpine
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: ["redis-server"]
          envFrom:
            - secretRef:
                name: outline-secrets
