apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: opencloud
  name: opencloud-app
  labels:
    app: opencloud-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencloud-app
  template:
    metadata:
      labels:
        app: opencloud-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: opencloud-app
          image: opencloudeu/opencloud-rolling:6.0.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: ["/bin/sh"]
          args: ["-c", "opencloud init || true; opencloud server"]
          envFrom:
            - secretRef:
                name: opencloud-secrets
          volumeMounts:
            - name: opencloud-app-storage
              mountPath: /etc/opencloud
              subPath: config
            - name: opencloud-app-storage
              mountPath: /var/lib/opencloud
              subPath: data
      volumes:
        - name: opencloud-app-storage
          persistentVolumeClaim:
            claimName: opencloud-app-pvc
