---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: opencloud
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: opencloud
  name: vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: opencloud
    serviceAccount: vault-auth
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: opencloud
  name: opencloud-secrets
spec:
  type: kv-v2
  mount: secret
  path: homecloud/opencloud
  destination:
    name: opencloud-secrets
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/part-of: opencloud
  vaultAuthRef: vault-auth
  refreshAfter: 1h
