apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: storage
  name: rustfs
  labels:
    app: rustfs

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rustfs
          image: rustfs/rustfs:1.0.0-alpha.90
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: ["/data"]
          envFrom:
            - secretRef:
                name: storage-secrets
          volumeMounts:
            - name: rustfs-storage
              mountPath: /data
      volumes:
        - name: rustfs-storage
          persistentVolumeClaim:
            claimName: rustfs-pvc
