apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: storage
  name: rustfs-pvc
  labels:
    app: rustfs

spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
