apiVersion: v1

kind: Service

metadata:
  namespace: storage
  name: rustfs
  labels:
    app: rustfs

spec:
  selector:
    app: rustfs
  type: ClusterIP
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
