---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: jellyfin
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: jellyfin
  name: vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: jellyfin
    serviceAccount: vault-auth
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: jellyfin
  name: jellyfin-secrets
spec:
  type: kv-v2
  mount: secret
  path: homecloud/jellyfin
  destination:
    name: jellyfin-secrets
    create: true
    overwrite: true
  vaultAuthRef: vault-auth
  refreshAfter: 1h
