apiVersion: v1

kind: Service

metadata:
  namespace: dev
  name: redis
  labels:
    app: redis

spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
