apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: monitoring
  name: tempo
  labels:
    app: tempo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tempo
          image: grafana/tempo:2.10.5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: [ "-config.file=/etc/tempo/tempo.yaml" ]
          volumeMounts:
            - name: tempo-storage
              mountPath: /var/tempo
            - name: tempo-config
              mountPath: /etc/tempo
      volumes:
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc
        - name: tempo-config
          configMap:
            name: tempo-configmap
