apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: monitoring
  name: tempo-pvc
  labels:
    app: tempo

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
