apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: docmost
  name: docmost-redis-deployment
  labels:
    app: docmost-redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost-redis
  template:
    metadata:
      labels:
        app: docmost-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: docmost-redis
          image: redis:8-alpine
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
          envFrom:
            - secretRef:
                name: docmost-secrets
          volumeMounts:
            - name: docmost-redis-storage
              mountPath: /data
      volumes:
        - name: docmost-redis-storage
          persistentVolumeClaim:
            claimName: docmost-redis-pvc
