apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: docmost
  name: docmost-redis-pvc
  labels:
    app: docmost-redis

spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
