apiVersion: v1

kind: Service

metadata:
  namespace: docmost
  name: docmost-redis-service
  labels:
    app: docmost-redis

spec:
  selector:
    app: docmost-redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
