apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: storage
  name: garage-pvc
  labels:
    app: garage

spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
