apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: monitoring
  name: grafana-mcp
  labels:
    app: grafana-mcp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-mcp
  template:
    metadata:
      labels:
        app: grafana-mcp
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: grafana-mcp
          image: grafana/mcp-grafana:0.12.1
          args: [ "--address", "0.0.0.0:8000", "--transport", "streamable-http" ]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: GRAFANA_URL
              value: "http://grafana.monitoring.svc.cluster.local:3000"
            - name: GRAFANA_SERVICE_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: GRAFANA_SERVICE_ACCOUNT_TOKEN
