apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: docmost
  name: docmost-app-deployment
  labels:
    app: docmost-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: docmost-app
  template:
    metadata:
      labels:
        app: docmost-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: docmost-app
          image: docmost/docmost:0.70.3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: docmost-secrets
          volumeMounts:
            - name: docmost-app-storage
              mountPath: /app/data/storage
      volumes:
        - name: docmost-app-storage
          persistentVolumeClaim:
            claimName: docmost-app-pvc
