apiVersion: v1

kind: Service

metadata:
  namespace: docmost
  name: docmost-app-service
  labels:
    app: docmost-app

spec:
  selector:
    app: docmost-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
