apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  namespace: outline
  name: outline-app-ingress
  labels:
    app: outline-app

spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: outline-app
      port:
        number: 80
  tls:
    - hosts:
        - outline
