apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: storage
  name: garage-data-pvc
  labels:
    app: garage-data

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
