apiVersion: v1

kind: Service

metadata:
  namespace: storage
  name: garage-data
  labels:
    app: garage-data

spec:
  selector:
    app: garage-data
  type: ClusterIP
  ports:
    - name: s3
      port: 3900
      targetPort: 3900
    - name: rpc
      port: 3901
      targetPort: 3901
