apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  namespace: communication
  name: mailpit-ingress
  labels:
    app: mailpit

spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: mailpit
      port:
        number: 80
  tls:
    - hosts:
        - mailpit
