apiVersion: v1

kind: Service

metadata:
  namespace: outline
  name: outline-redis-service
  labels:
    app: outline-redis

spec:
  selector:
    app: outline-redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
