apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: dev
  name: postgres-pvc
  labels:
    app: postgres

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
