apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - secrets.yaml
  - opentelemetry
  - s3-bucket-job.yaml

helmCharts:
  - name: grafana
    repo: https://grafana-community.github.io/helm-charts
    version: 12.4.2
    releaseName: grafana
    namespace: monitoring
    valuesFile: values-grafana.yaml
    includeCRDs: true

  - name: loki
    repo: https://grafana-community.github.io/helm-charts
    version: 17.1.7
    releaseName: loki
    namespace: monitoring
    valuesFile: values-loki.yaml
    includeCRDs: true

  - name: tempo
    repo: https://grafana-community.github.io/helm-charts
    version: 2.2.0
    releaseName: tempo
    namespace: monitoring
    valuesFile: values-tempo.yaml
    includeCRDs: true

  - name: grafana-mcp
    repo: https://grafana-community.github.io/helm-charts
    version: 0.16.0
    releaseName: grafana-mcp
    namespace: monitoring
    valuesFile: values-grafana-mcp.yaml
    includeCRDs: true

  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.10.0
    releaseName: alloy
    namespace: monitoring
    valuesFile: values-alloy.yaml
    includeCRDs: true

  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 29.10.0
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values-prometheus.yaml
    includeCRDs: true

  - name: thanos
    repo: https://thanos-community.github.io/helm-charts
    version: 0.20.0
    releaseName: thanos
    namespace: monitoring
    valuesFile: values-thanos.yaml
    includeCRDs: true

# adds namespace monitoring to thanos
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: monitoring
    target:
      labelSelector: "app.kubernetes.io/instance=thanos"
