apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: monitoring
  name: loki
  labels:
    app: loki

spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: loki
          image: grafana/loki:3.7.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: [ "-config.file=/etc/loki/loki.yaml" ]
          volumeMounts:
            - name: loki-storage
              mountPath: /loki
            - name: loki-config
              mountPath: /etc/loki
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-configmap
