apiVersion: v1

kind: Service

metadata:
  namespace: monitoring
  name: loki
  labels:
    app: loki

spec:
  selector:
    app: loki
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
