apiVersion: v1

kind: ConfigMap

metadata:
  namespace: secrets-system
  name: vault-config
  labels:
    app: vault

data:
  vault.hcl: |
    listener "tcp" {
      address       = "0.0.0.0:8200"
      tls_cert_file = "/vault/tls/tls.crt"
      tls_key_file  = "/vault/tls/tls.key"

      telemetry {
        unauthenticated_metrics_access = true
      }
    }

    storage "file" {
      path = "/vault/data"
    }

    telemetry {
      prometheus_retention_time = "120s"
      disable_hostname          = true
    }

    api_addr = "https://vault.secrets-system.svc.cluster.local:8200"

    disable_mlock = true

    ui = false
