apiVersion: v1

kind: ConfigMap

metadata:
  namespace: secrets-system
  name: vault-config
  labels:
    app: vault

data:
  vault.hcl: |
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "file" {
      path = "/vault/data"
    }

    disable_mlock = true

    ui = false
