apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: secrets-system
  name: vault-pvc
  labels:
    app: vault

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
