apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: monitoring
  name: grafana
  labels:
    app: grafana

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: grafana
          image: grafana/otel-lgtm:0.23.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: monitoring-secrets
          volumeMounts:
            - name: grafana-storage
              mountPath: /data
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
