apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: monitoring
  name: grafana-app-pvc
  labels:
    app: grafana-app

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
