---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tailscale
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: tailscale
  name: vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: tailscale
    serviceAccount: vault-auth
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: tailscale
  name: tailscale-secrets
spec:
  type: kv-v2
  mount: secret
  path: homecloud/tailscale
  destination:
    name: tailscale-secrets
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/part-of: tailscale
  vaultAuthRef: vault-auth
  refreshAfter: 1h
