apiVersion: apps/v1

kind: Deployment

metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak

spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: keycloak
          image: keycloak/keycloak:26.6.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: [ "start" ]
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-database:5432/keycloak
            - name: KC_DB_URL_PROPERTIES
              value: "?sslmode=verify-full&sslrootcert=/tls/ca.crt"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: POSTGRES_PASSWORD
            - name: KC_METRICS_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: keycloak-secrets
          volumeMounts:
            - name: keycloak-database-tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: keycloak-database-tls
          secret:
            secretName: keycloak-database-tls
            items:
              - key: ca.crt
                path: ca.crt
