apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: monitoring

resources:
  - rbac.yaml
  - daemonset.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: alloy-configmap
    files:
      - config/config.alloy
      - config/logs.alloy
      - config/otel.alloy
