apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: monitoring

resources:
  - instrumentation.yaml

helmCharts:
  - namespace: monitoring
    releaseName: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    name: opentelemetry-collector
    version: 0.152.0
    includeCRDs: false
    valuesInline:
      mode: deployment
      image:
        repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
      config:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
              http:
                endpoint: 0.0.0.0:4318
        processors:
          memory_limiter:
            check_interval: 1s
            limit_percentage: 75
            spike_limit_percentage: 15
          batch:
            send_batch_size: 10000
            timeout: 10s
        exporters:
          otlp:
            endpoint: grafana.monitoring.svc.cluster.local:4317
            tls:
              insecure: true
        service:
          pipelines:
            metrics:
              receivers: [ otlp ]
              processors: [ memory_limiter, batch ]
              exporters: [ otlp ]
            logs:
              receivers: [ otlp ]
              processors: [ memory_limiter, batch ]
              exporters: [ otlp ]
            traces:
              receivers: [ otlp ]
              processors: [ memory_limiter, batch ]
              exporters: [ otlp ]

  - namespace: monitoring
    releaseName: opentelemetry-operator
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    name: opentelemetry-operator
    version: 0.110.0
    includeCRDs: true
    valuesInline:
      manager:
        collectorImage:
          repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
