apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: outline
  name: outline-database-pvc
  labels:
    app: outline-database

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
