apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: monitoring
  name: mimir-pvc
  labels:
    app: mimir

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
