apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
  - namespace: argocd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    name: argo-cd
    version: 9.4.17
    includeCRDs: true
    valuesInline:
      configs:
        params:
          server.insecure: true
        cm:
          kustomize.buildOptions: --enable-helm
          oidc.config: |
            name: "Keycloak"
            issuer: "$argocd-secrets:OIDC_ISSUER"
            clientID: "argocd"
            clientSecret: "$argocd-secrets:CLIENT_SECRET"
            requestedScopes: ["openid", "profile", "email", "groups"]
          admin.enabled: "false"
        rbac:
          policy.default: role:readonly
          policy.csv: |
            g, argocd-admins, role:admin
          scopes: "[groups]"
