apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
  - namespace: argocd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    name: argo-cd
    version: 9.4.17
    includeCRDs: true
    valuesInline:
      configs:
        cm:
          kustomize.buildOptions: --enable-helm
        params:
          server.insecure: true
