apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: monitoring

helmCharts:
  - namespace: monitoring
    releaseName: grafana
    repo: https://grafana-community.github.io/helm-charts
    name: grafana
    version: 12.3.3
    valuesFile: values-grafana.yaml

  - namespace: monitoring
    releaseName: loki
    repo: https://grafana-community.github.io/helm-charts
    name: loki
    version: 16.1.1
    valuesFile: values-loki.yaml

  - namespace: monitoring
    releaseName: tempo
    repo: https://grafana-community.github.io/helm-charts
    name: tempo
    version: 2.1.2
    valuesFile: values-tempo.yaml

  - namespace: monitoring
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: 29.7.0
    valuesFile: values-prometheus.yaml
