server:
  securityContext:
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ ALL ]

  persistentVolume:
    enabled: true
    storageClass: longhorn
    size: 10Gi

  retention: "14d"

  extraFlags:
    - "web.enable-lifecycle"
    - "web.enable-remote-write-receiver"

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true

alertmanager:
  enabled: false

extraScrapeConfigs: |
  - job_name: vault
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /v1/sys/metrics
    params:
      format: [prometheus]
    static_configs:
      - targets: [vault.secrets-system.svc.cluster.local:8200]

  - job_name: vault-secrets-operator
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    static_configs:
      - targets: [vault-secrets-operator-metrics-service.secrets-system.svc.cluster.local:8443]
