securityContext:
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ ALL ]

persistence:
  enabled: true
  storageClassName: longhorn
  size: 4Gi

grafana.ini:
  tracing.opentelemetry.otlp:
    address: alloy.monitoring.svc.cluster.local:4317
    propagation: w3c

admin:
  existingSecret: monitoring-secrets
  userKey: GF_SECURITY_ADMIN_USER
  passwordKey: GF_SECURITY_ADMIN_PASSWORD

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 10s

      - name: Loki
        type: loki
        uid: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy

      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200
        access: proxy
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-5s"
            spanEndTimeShift: "5s"
            filterByTraceID: true
            filterBySpanID: true
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: loki
