apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: storage

resources:
  - namespace.yaml

helmCharts:
  - namespace: storage
    releaseName: longhorn
    repo: https://charts.longhorn.io
    name: longhorn
    version: 1.11.1
    includeCRDs: true
    valuesInline:
      defaultSettings:
        defaultDataPath: /mnt/homecloud/longhorn
        defaultReplicaCount: 1
      persistence:
        defaultClassReplicaCount: 1
