apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: storage

helmCharts:
  - namespace: storage
    releaseName: longhorn
    repo: https://charts.longhorn.io
    name: longhorn
    version: 1.11.1
    includeCRDs: true
    valuesInline:
      defaultSettings:
        defaultDataPath: /mnt/homecloud/longhorn
        defaultReplicaCount: 1
      defaultBackupStore:
        backupTarget: s3://longhorn-backups@eu-central-1/
        backupTargetCredentialSecret: storage-secrets
      persistence:
        defaultClassReplicaCount: 1
