apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  namespace: vaultwarden
  name: vaultwarden-app-pvc
  labels:
    app: vaultwarden-app

spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
